const express = require('express')
const bodyParser = require('body-parser')
const cors = require('cors')
const { join } = require('path')
const pages = require('./routes/pages')

module.exports = express()
  .set('view engine', 'pug')
  .set('views', join(__dirname, 'public', 'html'))
  .use(express.static('public'))
  .use(cors())
  .use(bodyParser.json())
  .use(bodyParser.urlencoded({ extended: true }))
  .use(pages)
